 SELECT UPPER(GEN.TEXTO_DESPLIEGUE) TEXTO_DESPLIEGUE
 , PRE.PRECIO, PRE.COD_PRODUCTO
 , PRE.PRECIO_ANTERIOR
 , PRE.INICIO_VIGENCIA
 , TO_CHAR(PRE.INICIO_VIGENCIA,'DD/MM/YYYY') INICIO_VIG , PRE.COD_CONVENIO
 , TO_CHAR(SYSDATE,'MMDDYYYY') FECHA_HOY , GEN.ESTADO TIPO_PRECIO 
 --, TO_CHAR(PRE.INICIO_VIGENCIA,'YYYY') ANO
 FROM GEN_ESTADOS GEN
 ,    ABA_PRECIOS PRE
 WHERE    GEN.COD_EMPRESA      = 4   AND GEN.COD_SUCURSAL     = 1   AND GEN.NOMBRE_TABLA     ='ABA_PRECIOS'
   AND GEN.NOMBRE_ATRIBUTO  = 'TIPO_PRECIO'
   AND PRE.COD_EMPRESA(+)   = GEN.COD_EMPRESA   AND PRE.COD_SUCURSAL(+)  = GEN.COD_SUCURSAL   AND PRE.TIPO_PRECIO(+)  = GEN.ESTADO   AND PRE.ESTADO(+)       = 'VIGENTE'
   AND PRE.INICIO_VIGENCIA(+) < SYSDATE
   --AND PRE.COD_PRODUCTO =  1013555
   AND  NVL(PRE.COD_CONVENIO,0) = 0
   AND UPPER(GEN.TEXTO_DESPLIEGUE) IN ('P.COMPRA','P.TRASPASO','P.HOSPITALIZADO')
   AND TO_CHAR(PRE.INICIO_VIGENCIA,'YYYY') in (2016,2017,2018)
   --AND UPPER(GEN.TEXTO_DESPLIEGUE) = 'P.TRASPASO'
   --OR UPPER(GEN.TEXTO_DESPLIEGUE) = 'P.HOSPITALIZADO'
 ORDER BY COD_PRODUCTO DESC  